import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "assistant-ui Starter App",
  description: "Generated by create-assistant-ui",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    return (
  <html lang="en">
    <body className={inter.className}>
      <header style={{ display: 'flex', alignItems: 'center', gap: '16px', background: '#e3f2fd', padding: '10px 20px' }}>
        <img src="/college-logo.png" alt="College Logo" style={{height:"60px"}} />
        <h1>Inderprastha Engineering College Chatbot</h1>
      </header>
      {children}
    </body>
  </html>
);

   
  );
}
